server:
  port: 8082


spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: BOOKINGSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/RoomBooking?createDatabaseIfNotExist=true
    username: root
    password: 2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


